# Generated by Django 4.2.4 on 2023-08-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twix", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="follow",
            new_name="follows",
        ),
    ]
